syntax = "proto3";

option csharp_namespace = "IISNotionSearch.Infrastructure.Grpc";

package weather;

service WeatherService {
  rpc GetWeatherByCity (WeatherRequest) returns (WeatherResponse);
}

message WeatherRequest {
  string city_name = 1;
}

message WeatherResponse {
  repeated CityWeather results = 1;
  string last_updated = 2;
}

message CityWeather {
  string city_name = 1;
  string temperature = 2;
  string humidity = 3;
  string condition = 4;
  string wind_speed = 5;
  string wind_direction = 6;
}
