// <auto-generated/>
#pragma warning disable CS0618
using IISNotionSearch.Infrastructure.NotionClient.V1.Pages.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace IISNotionSearch.Infrastructure.NotionClient.V1.Pages
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\pages
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PagesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the IISNotionSearch.Infrastructure.NotionClient.v1.pages.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::IISNotionSearch.Infrastructure.NotionClient.V1.Pages.Item.WithPage_ItemRequestBuilder"/></returns>
        public global::IISNotionSearch.Infrastructure.NotionClient.V1.Pages.Item.WithPage_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("page_id", position);
                return new global::IISNotionSearch.Infrastructure.NotionClient.V1.Pages.Item.WithPage_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IISNotionSearch.Infrastructure.NotionClient.V1.Pages.PagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PagesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/pages", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IISNotionSearch.Infrastructure.NotionClient.V1.Pages.PagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PagesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/pages", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
