// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IISNotionSearch.Infrastructure.NotionClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BlockObjectWithSingleLevelOfChildrenRequestMember8_code : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The caption property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::IISNotionSearch.Infrastructure.NotionClient.Models.RichTextItemRequest>? Caption { get; set; }
#nullable restore
#else
        public List<global::IISNotionSearch.Infrastructure.NotionClient.Models.RichTextItemRequest> Caption { get; set; }
#endif
        /// <summary>The language property</summary>
        public global::IISNotionSearch.Infrastructure.NotionClient.Models.LanguageRequest? Language { get; set; }
        /// <summary>The rich_text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::IISNotionSearch.Infrastructure.NotionClient.Models.RichTextItemRequest>? RichText { get; set; }
#nullable restore
#else
        public List<global::IISNotionSearch.Infrastructure.NotionClient.Models.RichTextItemRequest> RichText { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IISNotionSearch.Infrastructure.NotionClient.Models.BlockObjectWithSingleLevelOfChildrenRequestMember8_code"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IISNotionSearch.Infrastructure.NotionClient.Models.BlockObjectWithSingleLevelOfChildrenRequestMember8_code CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::IISNotionSearch.Infrastructure.NotionClient.Models.BlockObjectWithSingleLevelOfChildrenRequestMember8_code();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "caption", n => { Caption = n.GetCollectionOfObjectValues<global::IISNotionSearch.Infrastructure.NotionClient.Models.RichTextItemRequest>(global::IISNotionSearch.Infrastructure.NotionClient.Models.RichTextItemRequest.CreateFromDiscriminatorValue)?.AsList(); } },
                { "language", n => { Language = n.GetEnumValue<global::IISNotionSearch.Infrastructure.NotionClient.Models.LanguageRequest>(); } },
                { "rich_text", n => { RichText = n.GetCollectionOfObjectValues<global::IISNotionSearch.Infrastructure.NotionClient.Models.RichTextItemRequest>(global::IISNotionSearch.Infrastructure.NotionClient.Models.RichTextItemRequest.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::IISNotionSearch.Infrastructure.NotionClient.Models.RichTextItemRequest>("caption", Caption);
            writer.WriteEnumValue<global::IISNotionSearch.Infrastructure.NotionClient.Models.LanguageRequest>("language", Language);
            writer.WriteCollectionOfObjectValues<global::IISNotionSearch.Infrastructure.NotionClient.Models.RichTextItemRequest>("rich_text", RichText);
        }
    }
}
#pragma warning restore CS0618
