// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IISNotionSearch.Infrastructure.NotionClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BlockObjectWithSingleLevelOfChildrenRequestMember29_synced_block : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The children property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::IISNotionSearch.Infrastructure.NotionClient.Models.BlockObjectRequestWithoutChildren>? Children { get; set; }
#nullable restore
#else
        public List<global::IISNotionSearch.Infrastructure.NotionClient.Models.BlockObjectRequestWithoutChildren> Children { get; set; }
#endif
        /// <summary>The synced_from property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IISNotionSearch.Infrastructure.NotionClient.Models.BlockObjectWithSingleLevelOfChildrenRequestMember29_synced_block_synced_from? SyncedFrom { get; set; }
#nullable restore
#else
        public global::IISNotionSearch.Infrastructure.NotionClient.Models.BlockObjectWithSingleLevelOfChildrenRequestMember29_synced_block_synced_from SyncedFrom { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IISNotionSearch.Infrastructure.NotionClient.Models.BlockObjectWithSingleLevelOfChildrenRequestMember29_synced_block"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IISNotionSearch.Infrastructure.NotionClient.Models.BlockObjectWithSingleLevelOfChildrenRequestMember29_synced_block CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::IISNotionSearch.Infrastructure.NotionClient.Models.BlockObjectWithSingleLevelOfChildrenRequestMember29_synced_block();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "children", n => { Children = n.GetCollectionOfObjectValues<global::IISNotionSearch.Infrastructure.NotionClient.Models.BlockObjectRequestWithoutChildren>(global::IISNotionSearch.Infrastructure.NotionClient.Models.BlockObjectRequestWithoutChildren.CreateFromDiscriminatorValue)?.AsList(); } },
                { "synced_from", n => { SyncedFrom = n.GetObjectValue<global::IISNotionSearch.Infrastructure.NotionClient.Models.BlockObjectWithSingleLevelOfChildrenRequestMember29_synced_block_synced_from>(global::IISNotionSearch.Infrastructure.NotionClient.Models.BlockObjectWithSingleLevelOfChildrenRequestMember29_synced_block_synced_from.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::IISNotionSearch.Infrastructure.NotionClient.Models.BlockObjectRequestWithoutChildren>("children", Children);
            writer.WriteObjectValue<global::IISNotionSearch.Infrastructure.NotionClient.Models.BlockObjectWithSingleLevelOfChildrenRequestMember29_synced_block_synced_from>("synced_from", SyncedFrom);
        }
    }
}
#pragma warning restore CS0618
