// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace IISNotionSearch.Infrastructure.NotionClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Error_api_404_code
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "object_not_found")]
        #pragma warning disable CS1591
        Object_not_found,
        #pragma warning restore CS1591
    }
}
