// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace IISNotionSearch.Infrastructure.NotionClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::IISNotionSearch.Infrastructure.NotionClient.Models.AgentIdParentForBlockBasedObjectResponse"/>, <see cref="global::IISNotionSearch.Infrastructure.NotionClient.Models.BlockIdParentForBlockBasedObjectResponse"/>, <see cref="global::IISNotionSearch.Infrastructure.NotionClient.Models.DatabaseParentResponse"/>, <see cref="global::IISNotionSearch.Infrastructure.NotionClient.Models.DataSourceParentResponse"/>, <see cref="global::IISNotionSearch.Infrastructure.NotionClient.Models.PageIdParentForBlockBasedObjectResponse"/>, <see cref="global::IISNotionSearch.Infrastructure.NotionClient.Models.WorkspaceParentForBlockBasedObjectResponse"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ParentForBlockBasedObjectResponse : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::IISNotionSearch.Infrastructure.NotionClient.Models.AgentIdParentForBlockBasedObjectResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IISNotionSearch.Infrastructure.NotionClient.Models.AgentIdParentForBlockBasedObjectResponse? AgentIdParentForBlockBasedObjectResponse { get; set; }
#nullable restore
#else
        public global::IISNotionSearch.Infrastructure.NotionClient.Models.AgentIdParentForBlockBasedObjectResponse AgentIdParentForBlockBasedObjectResponse { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IISNotionSearch.Infrastructure.NotionClient.Models.BlockIdParentForBlockBasedObjectResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IISNotionSearch.Infrastructure.NotionClient.Models.BlockIdParentForBlockBasedObjectResponse? BlockIdParentForBlockBasedObjectResponse { get; set; }
#nullable restore
#else
        public global::IISNotionSearch.Infrastructure.NotionClient.Models.BlockIdParentForBlockBasedObjectResponse BlockIdParentForBlockBasedObjectResponse { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IISNotionSearch.Infrastructure.NotionClient.Models.DatabaseParentResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IISNotionSearch.Infrastructure.NotionClient.Models.DatabaseParentResponse? DatabaseParentResponse { get; set; }
#nullable restore
#else
        public global::IISNotionSearch.Infrastructure.NotionClient.Models.DatabaseParentResponse DatabaseParentResponse { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IISNotionSearch.Infrastructure.NotionClient.Models.DataSourceParentResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IISNotionSearch.Infrastructure.NotionClient.Models.DataSourceParentResponse? DataSourceParentResponse { get; set; }
#nullable restore
#else
        public global::IISNotionSearch.Infrastructure.NotionClient.Models.DataSourceParentResponse DataSourceParentResponse { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IISNotionSearch.Infrastructure.NotionClient.Models.PageIdParentForBlockBasedObjectResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IISNotionSearch.Infrastructure.NotionClient.Models.PageIdParentForBlockBasedObjectResponse? PageIdParentForBlockBasedObjectResponse { get; set; }
#nullable restore
#else
        public global::IISNotionSearch.Infrastructure.NotionClient.Models.PageIdParentForBlockBasedObjectResponse PageIdParentForBlockBasedObjectResponse { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::IISNotionSearch.Infrastructure.NotionClient.Models.WorkspaceParentForBlockBasedObjectResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::IISNotionSearch.Infrastructure.NotionClient.Models.WorkspaceParentForBlockBasedObjectResponse? WorkspaceParentForBlockBasedObjectResponse { get; set; }
#nullable restore
#else
        public global::IISNotionSearch.Infrastructure.NotionClient.Models.WorkspaceParentForBlockBasedObjectResponse WorkspaceParentForBlockBasedObjectResponse { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::IISNotionSearch.Infrastructure.NotionClient.Models.ParentForBlockBasedObjectResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::IISNotionSearch.Infrastructure.NotionClient.Models.ParentForBlockBasedObjectResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::IISNotionSearch.Infrastructure.NotionClient.Models.ParentForBlockBasedObjectResponse();
            if("agentIdParentForBlockBasedObjectResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AgentIdParentForBlockBasedObjectResponse = new global::IISNotionSearch.Infrastructure.NotionClient.Models.AgentIdParentForBlockBasedObjectResponse();
            }
            else if("blockIdParentForBlockBasedObjectResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BlockIdParentForBlockBasedObjectResponse = new global::IISNotionSearch.Infrastructure.NotionClient.Models.BlockIdParentForBlockBasedObjectResponse();
            }
            else if("dataSourceParentResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DataSourceParentResponse = new global::IISNotionSearch.Infrastructure.NotionClient.Models.DataSourceParentResponse();
            }
            else if("databaseParentResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DatabaseParentResponse = new global::IISNotionSearch.Infrastructure.NotionClient.Models.DatabaseParentResponse();
            }
            else if("pageIdParentForBlockBasedObjectResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.PageIdParentForBlockBasedObjectResponse = new global::IISNotionSearch.Infrastructure.NotionClient.Models.PageIdParentForBlockBasedObjectResponse();
            }
            else if("workspaceParentForBlockBasedObjectResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.WorkspaceParentForBlockBasedObjectResponse = new global::IISNotionSearch.Infrastructure.NotionClient.Models.WorkspaceParentForBlockBasedObjectResponse();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(AgentIdParentForBlockBasedObjectResponse != null)
            {
                return AgentIdParentForBlockBasedObjectResponse.GetFieldDeserializers();
            }
            else if(BlockIdParentForBlockBasedObjectResponse != null)
            {
                return BlockIdParentForBlockBasedObjectResponse.GetFieldDeserializers();
            }
            else if(DatabaseParentResponse != null)
            {
                return DatabaseParentResponse.GetFieldDeserializers();
            }
            else if(DataSourceParentResponse != null)
            {
                return DataSourceParentResponse.GetFieldDeserializers();
            }
            else if(PageIdParentForBlockBasedObjectResponse != null)
            {
                return PageIdParentForBlockBasedObjectResponse.GetFieldDeserializers();
            }
            else if(WorkspaceParentForBlockBasedObjectResponse != null)
            {
                return WorkspaceParentForBlockBasedObjectResponse.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(AgentIdParentForBlockBasedObjectResponse != null)
            {
                writer.WriteObjectValue<global::IISNotionSearch.Infrastructure.NotionClient.Models.AgentIdParentForBlockBasedObjectResponse>(null, AgentIdParentForBlockBasedObjectResponse);
            }
            else if(BlockIdParentForBlockBasedObjectResponse != null)
            {
                writer.WriteObjectValue<global::IISNotionSearch.Infrastructure.NotionClient.Models.BlockIdParentForBlockBasedObjectResponse>(null, BlockIdParentForBlockBasedObjectResponse);
            }
            else if(DatabaseParentResponse != null)
            {
                writer.WriteObjectValue<global::IISNotionSearch.Infrastructure.NotionClient.Models.DatabaseParentResponse>(null, DatabaseParentResponse);
            }
            else if(DataSourceParentResponse != null)
            {
                writer.WriteObjectValue<global::IISNotionSearch.Infrastructure.NotionClient.Models.DataSourceParentResponse>(null, DataSourceParentResponse);
            }
            else if(PageIdParentForBlockBasedObjectResponse != null)
            {
                writer.WriteObjectValue<global::IISNotionSearch.Infrastructure.NotionClient.Models.PageIdParentForBlockBasedObjectResponse>(null, PageIdParentForBlockBasedObjectResponse);
            }
            else if(WorkspaceParentForBlockBasedObjectResponse != null)
            {
                writer.WriteObjectValue<global::IISNotionSearch.Infrastructure.NotionClient.Models.WorkspaceParentForBlockBasedObjectResponse>(null, WorkspaceParentForBlockBasedObjectResponse);
            }
        }
    }
}
#pragma warning restore CS0618
